### PR TITLE
Add xESMF notebook

### PR DESCRIPTION
**Pull request by r-ford**
Same as #26 but without branch conflicts

### CODE REVIEW

**Comment by r-ford** [comment]
It's raising a [`CancelledError`](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/4226753207/jobs/7341297209#step:13:89) for the new notebook related to asyncio. @mgrover1, have you seen something like this before?

**Comment by mgrover1** [comment]
@r-ford - I suspect it is timing out due to a long computation... there are 27 datasets being regridded in the notebook, my suggestion would be scale back a little bit, maybe look at 3-5 of them?

**Comment by r-ford** [comment]
The problem ended up being from one model raising a `MemoryError` while regridding. I used a try/except block, so it ran fine locally. But I guess binderbot didn't like it.

**Review by brian-rose — COMMENTED** [review]
This is great @r-ford! A good example of a real-world use case (multi-model mean maps) making it into the cookbook.

I have just a few nit-picky comments:

1. Can we change the section heading "Download the data" to something more like "Access the data". We are trying to advance a "data proximate computing" paradigm and should avoid wording that steers people toward bulk downloading of data as a first workflow step.
2. The DOI links in the Reference section are not rendering as links.

**Comment by brian-rose** [comment]
I also suggest leaving an open issue in this repo about the one model causing a memory error on the binder. I suspect that will go away when we spin up our next-generation Pythia binder on Jetstream2 -- and in fact this could make a useful performance benchmark test.

**Comment by r-ford** [comment]
@brian-rose Thanks! I've made those edits.

**Review by mgrover1 — APPROVED** [review]
I really like this example @r-ford ! Great work.

**Comment by brian-rose** [comment]
Nice work @r-ford!

**Pull request merged**
