### PR TITLE
ADD: Add new notebook calculating ENSO with intake-esgf

### PR DESCRIPTION
**Pull request by mgrover1**
Show how to use intake-esgf to access data, apply ENSO calculations, and visualize using hvPlot.

### CODE REVIEW

**Comment by r-ford** [comment]
Nice! I'll take a look at this today. 

It seems like the [preview action is failing](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/6461391358/job/17540965044) because the environment is not being updated to include `intake_esgf`. Is the solution to just update the env on main first, or is there some config option that can be set?

**Comment by brian-rose** [comment]
> It seems like the [preview action is failing](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/6461391358/job/17540965044) because the environment is not being updated to include `intake_esgf`. Is the solution to just update the env on main first, or is there some config option that can be set?

This is a current limitation of our build actions (https://github.com/ProjectPythia/cookbook-actions/issues/77). This "edge case" of building on Binder with secrets and a change in the environment file is not something we currently handle. There are complications around the scope rules for using secrets that we haven't solved.

The workaround is as Rob says: open a simple PR just adding the new package to the environment file and merge it into main even though it won't build and preview properly. Then proceed with this PR.

**Comment by mgrover1** [comment]
@brian-rose @r-ford - I submitted a PR with the suggested way forward 😄

**Comment by mgrover1** [comment]
@brian-rose - unpinning numpy here brought back the numba issues... I will submit a PR to revert the numpy version.

**Comment by mgrover1** [comment]
@brian-rose @r-ford numba is causing issues with the main execution environment. The opendap issue has been resolved, I am not sure what to do about rebuilding the conda environment for the book here. Those recent PRs did not trigger a reinstallation of numba.

**Pull request merged**
