### PR TITLE
Try to fix build

### PR DESCRIPTION
**Pull request by r-ford**
Same as https://github.com/ProjectPythia/cmip6-cookbook/pull/32

### CODE REVIEW

**Comment by r-ford** [comment]
Based on the [`KeyError` here](https://github.com/ProjectPythia/cmip6-cookbook/actions/runs/3727857857/jobs/6322365734#step:11:174), it looks like it is trying to find `imbalance` in the coordinates. I also can't recreate the error locally.

**Comment by r-ford** [comment]
@brian-rose, I'm trying to use a previous Xarray version, but it doesn't look like the execution environment gets updated during the build. Is there a way to specify that I want to update it?

**Comment by brian-rose** [comment]
> @brian-rose, I'm trying to use a previous Xarray version, but it doesn't look like the execution environment gets updated during the build. Is there a way to specify that I want to update it?

Since you're using `execute_notebooks: binder`, the execution environment uses the image from the main branch of the repo. This is a limitation in how we are doing things right now. Changes to the `environment.yml` file in the PR will not have any effect on the Binder environment.

**Comment by brian-rose** [comment]
A simple workaround is just to merge your environment changes into main, and then test your new code. Sort of a hack, but that will accomplish what you want.

**Comment by brian-rose** [comment]
This line of code [here](https://github.com/ProjectPythia/cookbook-actions/blob/d0195662621289bb5cda370457ed1051ab033ff0/.github/workflows/build-book.yaml#L132) in the cookbook actions repo is where the call to binderbot is made, and we are currently hard-coding to the `main` branch.

**Comment by r-ford** [comment]
Ok, that seemed to work. I'll just merge to see if it fixes the main branch.

**Pull request merged**
